"use strict";
exports.__esModule = true;
var Department_1 = require("./Department");
var department1 = new Department_1.Department(1, "Sale");
var department2 = new Department_1.Department(2, "Marketing");
var department3 = new Department_1.Department(3, "BOD");
var department4 = new Department_1.Department(4, "Kỹ thuật");
console.log("Thông tin khách hàng số 1");
department1.printInfo();
console.log("Thông tin khách hàng số 2");
(0, Department_1.printInfoDepartment)(department2);
